[2025-06-20T15:33:58.173+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-20T15:33:58.203+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_staging.fetch_shot_chart_and_load_to_stage manual__2025-06-20T15:33:38.710119+00:00 [queued]>
[2025-06-20T15:33:58.213+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_staging.fetch_shot_chart_and_load_to_stage manual__2025-06-20T15:33:38.710119+00:00 [queued]>
[2025-06-20T15:33:58.214+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-20T15:33:58.273+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_shot_chart_and_load_to_stage> on 2025-06-20 15:33:38.710119+00:00
[2025-06-20T15:33:58.279+0000] {standard_task_runner.py:63} INFO - Started process 3018 to run task
[2025-06-20T15:33:58.286+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_staging', 'fetch_shot_chart_and_load_to_stage', 'manual__2025-06-20T15:33:38.710119+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpa_bql4b1']
[2025-06-20T15:33:58.288+0000] {standard_task_runner.py:91} INFO - Job 272: Subtask fetch_shot_chart_and_load_to_stage
[2025-06-20T15:33:58.390+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_staging.fetch_shot_chart_and_load_to_stage manual__2025-06-20T15:33:38.710119+00:00 [running]> on host 5ea278fdf3a6
[2025-06-20T15:33:58.561+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_staging' AIRFLOW_CTX_TASK_ID='fetch_shot_chart_and_load_to_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-06-20T15:33:38.710119+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-20T15:33:38.710119+00:00'
[2025-06-20T15:33:58.563+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-20T15:33:58.590+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/etl_pipeline.py:174 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-20T15:34:02.414+0000] {etl_pipeline.py:190} INFO - Processed game on 2024-10-22 between BOS and NYK.
[2025-06-20T15:34:09.139+0000] {etl_pipeline.py:190} INFO - Processed game on 2024-10-22 between LAL and MIN.
[2025-06-20T15:34:16.046+0000] {etl_pipeline.py:190} INFO - Processed game on 2024-10-23 between DET and IND.
[2025-06-20T15:34:16.053+0000] {etl_pipeline.py:98} INFO - Ensuring table 'stgshotchart' exists...
[2025-06-20T15:34:16.055+0000] {etl_pipeline.py:100} INFO - Table 'stgshotchart' is ready.
[2025-06-20T15:34:16.056+0000] {etl_pipeline.py:110} INFO - Truncating table stgshotchart and restarting identity columns...
[2025-06-20T15:34:16.059+0000] {etl_pipeline.py:115} INFO - Loading 524 rows into stgshotchart...
[2025-06-20T15:34:16.064+0000] {etl_pipeline.py:120} ERROR - Database execution error: column "home_team" of relation "stgshotchart" does not exist
LINE 1: ...me_remaining, player, make_miss, value, distance, home_team,...
                                                             ^

[2025-06-20T15:34:16.064+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-20T15:34:16.065+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 196, in fetch_and_load_shot_chart_to_stage
    load_df_to_postgres(df=final_df, table_name=table_name, conn_string=conn_string, create_table_query=create_table_query)
  File "/opt/airflow/dags/etl_pipeline.py", line 116, in load_df_to_postgres
    execute_values(cursor, sql_query, data_tuples)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "home_team" of relation "stgshotchart" does not exist
LINE 1: ...me_remaining, player, make_miss, value, distance, home_team,...
                                                             ^

[2025-06-20T15:34:16.082+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_etl_to_staging, task_id=fetch_shot_chart_and_load_to_stage, run_id=manual__2025-06-20T15:33:38.710119+00:00, execution_date=20250620T153338, start_date=20250620T153358, end_date=20250620T153416
[2025-06-20T15:34:16.116+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 272 for task fetch_shot_chart_and_load_to_stage (column "home_team" of relation "stgshotchart" does not exist
LINE 1: ...me_remaining, player, make_miss, value, distance, home_team,...
                                                             ^
; 3018)
[2025-06-20T15:34:16.134+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-20T15:34:16.152+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-20T15:34:16.184+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
