[2025-06-14T16:18:27.584+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T16:18:27.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_schedule_and_load_to_postgres manual__2025-06-14T16:18:25.067261+00:00 [queued]>
[2025-06-14T16:18:27.669+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_schedule_and_load_to_postgres manual__2025-06-14T16:18:25.067261+00:00 [queued]>
[2025-06-14T16:18:27.671+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-14T16:18:27.726+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_schedule_and_load_to_postgres> on 2025-06-14 16:18:25.067261+00:00
[2025-06-14T16:18:27.741+0000] {standard_task_runner.py:63} INFO - Started process 508 to run task
[2025-06-14T16:18:27.752+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_postgres', 'fetch_schedule_and_load_to_postgres', 'manual__2025-06-14T16:18:25.067261+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpyqkxcfao']
[2025-06-14T16:18:27.757+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask fetch_schedule_and_load_to_postgres
[2025-06-14T16:18:28.008+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_postgres.fetch_schedule_and_load_to_postgres manual__2025-06-14T16:18:25.067261+00:00 [running]> on host abedc69fc846
[2025-06-14T16:18:28.289+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_schedule_and_load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T16:18:25.067261+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T16:18:25.067261+00:00'
[2025-06-14T16:18:28.290+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T16:18:28.405+0000] {logging_mixin.py:188} INFO - Initializing Selenium driver...
[2025-06-14T16:18:28.420+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T16:18:28.422+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 64, in _binary_paths
    raise ValueError(f"The path is not a valid file: {path}")
ValueError: The path is not a valid file: /usr/bin/chromium-driver

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 52, in fetch_and_load_schedule_to_stage
    selenium_driver = webdriver.Chrome(service=service, options=options)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    if finder.get_browser_path():
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-06-14T16:18:28.486+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_etl_to_postgres, task_id=fetch_schedule_and_load_to_postgres, run_id=manual__2025-06-14T16:18:25.067261+00:00, execution_date=20250614T161825, start_date=20250614T161827, end_date=20250614T161828
[2025-06-14T16:18:28.568+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task fetch_schedule_and_load_to_postgres (Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
; 508)
[2025-06-14T16:18:28.615+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-14T16:18:28.630+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
