[2025-06-20T18:52:51.931+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-20T18:52:51.977+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_transform_to_dwh.load_dim_match manual__2025-06-20T18:52:49.633420+00:00 [queued]>
[2025-06-20T18:52:51.994+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_transform_to_dwh.load_dim_match manual__2025-06-20T18:52:49.633420+00:00 [queued]>
[2025-06-20T18:52:51.995+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-20T18:52:52.094+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_dim_match> on 2025-06-20 18:52:49.633420+00:00
[2025-06-20T18:52:52.103+0000] {standard_task_runner.py:63} INFO - Started process 4522 to run task
[2025-06-20T18:52:52.109+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_transform_to_dwh', 'load_dim_match', 'manual__2025-06-20T18:52:49.633420+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpgd1y37e0']
[2025-06-20T18:52:52.111+0000] {standard_task_runner.py:91} INFO - Job 317: Subtask load_dim_match
[2025-06-20T18:52:52.249+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_transform_to_dwh.load_dim_match manual__2025-06-20T18:52:49.633420+00:00 [running]> on host 5ea278fdf3a6
[2025-06-20T18:52:52.450+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_transform_to_dwh' AIRFLOW_CTX_TASK_ID='load_dim_match' AIRFLOW_CTX_EXECUTION_DATE='2025-06-20T18:52:49.633420+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-20T18:52:49.633420+00:00'
[2025-06-20T18:52:52.451+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-20T18:52:52.476+0000] {etl_pipeline.py:450} INFO - Ensuring dimension table 'dimmatch' exists...
[2025-06-20T18:52:52.479+0000] {etl_pipeline.py:456} ERROR - Failed to create or load dimension 'dimmatch'. Error: column "gamedate" specified more than once

[2025-06-20T18:52:52.480+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-20T18:52:52.482+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 451, in fetch_dim_match
    cursor.execute(create_table_query)
psycopg2.errors.DuplicateColumn: column "gamedate" specified more than once

[2025-06-20T18:52:52.504+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_transform_to_dwh, task_id=load_dim_match, run_id=manual__2025-06-20T18:52:49.633420+00:00, execution_date=20250620T185249, start_date=20250620T185251, end_date=20250620T185252
[2025-06-20T18:52:52.566+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 317 for task load_dim_match (column "gamedate" specified more than once
; 4522)
[2025-06-20T18:52:52.605+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-20T18:52:52.621+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
