[2025-06-21T19:47:37.523+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-21T19:47:37.784+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_staging.fetch_shot_chart_and_load_to_stage manual__2025-06-21T18:11:57.608096+00:00 [queued]>
[2025-06-21T19:47:40.270+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_staging.fetch_shot_chart_and_load_to_stage manual__2025-06-21T18:11:57.608096+00:00 [queued]>
[2025-06-21T19:47:40.271+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-21T19:47:40.477+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_shot_chart_and_load_to_stage> on 2025-06-21 18:11:57.608096+00:00
[2025-06-21T19:47:40.531+0000] {standard_task_runner.py:63} INFO - Started process 6953 to run task
[2025-06-21T19:47:40.538+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_staging', 'fetch_shot_chart_and_load_to_stage', 'manual__2025-06-21T18:11:57.608096+00:00', '--job-id', '449', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp_1b1kn7d']
[2025-06-21T19:47:40.541+0000] {standard_task_runner.py:91} INFO - Job 449: Subtask fetch_shot_chart_and_load_to_stage
[2025-06-21T19:47:41.000+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_staging.fetch_shot_chart_and_load_to_stage manual__2025-06-21T18:11:57.608096+00:00 [running]> on host 5ea278fdf3a6
[2025-06-21T19:47:41.540+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_staging' AIRFLOW_CTX_TASK_ID='fetch_shot_chart_and_load_to_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-06-21T18:11:57.608096+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-21T18:11:57.608096+00:00'
[2025-06-21T19:47:41.541+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-21T19:47:42.808+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/etl_pipeline.py:174 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-21T19:47:51.656+0000] {etl_pipeline.py:69} WARNING - Błąd podczas wywołania get_shot_chart_with_retry: HTTPSConnectionPool(host='www.basketball-reference.com', port=443): Max retries exceeded with url: /boxscores/shot-chart/202410220BOS.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x764814772220>: Failed to resolve 'www.basketball-reference.com' ([Errno -3] Temporary failure in name resolution)")). Próba 1 z 5...
[2025-06-21T19:48:01.779+0000] {etl_pipeline.py:69} WARNING - Błąd podczas wywołania get_shot_chart_with_retry: HTTPSConnectionPool(host='www.basketball-reference.com', port=443): Max retries exceeded with url: /boxscores/?month=10&year=2024&day=22 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x76481442ed00>: Failed to resolve 'www.basketball-reference.com' ([Errno -3] Temporary failure in name resolution)")). Próba 2 z 5...
