[2025-06-19T11:42:34.928+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-19T11:42:34.961+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_transform_to_dwh.fetch_dim_team_from_transform_and_load manual__2025-06-19T11:40:30.419149+00:00 [queued]>
[2025-06-19T11:42:34.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_transform_to_dwh.fetch_dim_team_from_transform_and_load manual__2025-06-19T11:40:30.419149+00:00 [queued]>
[2025-06-19T11:42:34.972+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-19T11:42:35.184+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_dim_team_from_transform_and_load> on 2025-06-19 11:40:30.419149+00:00
[2025-06-19T11:42:35.190+0000] {standard_task_runner.py:63} INFO - Started process 2608 to run task
[2025-06-19T11:42:35.194+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_transform_to_dwh', 'fetch_dim_team_from_transform_and_load', 'manual__2025-06-19T11:40:30.419149+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpro0z6qqf']
[2025-06-19T11:42:35.196+0000] {standard_task_runner.py:91} INFO - Job 120: Subtask fetch_dim_team_from_transform_and_load
[2025-06-19T11:42:35.281+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_transform_to_dwh.fetch_dim_team_from_transform_and_load manual__2025-06-19T11:40:30.419149+00:00 [running]> on host 11d91b3c2b82
[2025-06-19T11:42:35.426+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_transform_to_dwh' AIRFLOW_CTX_TASK_ID='fetch_dim_team_from_transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T11:40:30.419149+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T11:40:30.419149+00:00'
[2025-06-19T11:42:35.427+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-19T11:42:35.451+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/etl_pipeline.py:626 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-19T11:42:35.662+0000] {logging_mixin.py:188} INFO - Table dimteam is ready.
[2025-06-19T11:42:35.665+0000] {logging_mixin.py:188} INFO - Failed to load data into dimteam: column "teamid" does not exist
LINE 4:         teamid,
                ^
HINT:  There is a column named "teamid" in table "dimteam", but it cannot be referenced from this part of the query.
[2025-06-19T11:42:35.665+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-19T11:42:35.666+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 648, in fetch_dim_team
    cursor.execute(insert_query)
psycopg2.errors.UndefinedColumn: column "teamid" does not exist
LINE 4:         teamid,
                ^
HINT:  There is a column named "teamid" in table "dimteam", but it cannot be referenced from this part of the query.

[2025-06-19T11:42:35.681+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_transform_to_dwh, task_id=fetch_dim_team_from_transform_and_load, run_id=manual__2025-06-19T11:40:30.419149+00:00, execution_date=20250619T114030, start_date=20250619T114234, end_date=20250619T114235
[2025-06-19T11:42:35.723+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 120 for task fetch_dim_team_from_transform_and_load (column "teamid" does not exist
LINE 4:         teamid,
                ^
HINT:  There is a column named "teamid" in table "dimteam", but it cannot be referenced from this part of the query.
; 2608)
[2025-06-19T11:42:35.745+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-19T11:42:35.764+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T11:42:35.794+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
