[2025-06-15T20:41:18.840+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T20:41:18.868+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-15T20:41:18.876+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-15T20:41:18.877+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-15T20:41:18.920+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_load_teams_to_stage> on 2025-06-08 00:00:00+00:00
[2025-06-15T20:41:18.926+0000] {standard_task_runner.py:63} INFO - Started process 922 to run task
[2025-06-15T20:41:18.931+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_postgres', 'fetch_and_load_teams_to_stage', 'scheduled__2025-06-08T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp2f8jcotc']
[2025-06-15T20:41:18.932+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask fetch_and_load_teams_to_stage
[2025-06-15T20:41:19.063+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [running]> on host 1c61638087f1
[2025-06-15T20:41:19.226+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_and_load_teams_to_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T00:00:00+00:00'
[2025-06-15T20:41:19.227+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T20:41:19.246+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T20:41:19.247+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 283, in fetch_and_load_teams_to_stage
    cur.copy_expert(sql_copy_command, f)
psycopg2.errors.UndefinedTable: relation "stgteam" does not exist

[2025-06-15T20:41:19.263+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_etl_to_postgres, task_id=fetch_and_load_teams_to_stage, run_id=scheduled__2025-06-08T00:00:00+00:00, execution_date=20250608T000000, start_date=20250615T204118, end_date=20250615T204119
[2025-06-15T20:41:19.304+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task fetch_and_load_teams_to_stage (relation "stgteam" does not exist
; 922)
[2025-06-15T20:41:19.344+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-15T20:41:19.362+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-15T20:41:19.394+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
