[2025-06-19T10:46:56.105+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-19T10:46:56.253+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_staging_to_transform.fetch_pbp_from_stg_and_transform manual__2025-06-19T10:46:54.023225+00:00 [queued]>
[2025-06-19T10:46:56.299+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_staging_to_transform.fetch_pbp_from_stg_and_transform manual__2025-06-19T10:46:54.023225+00:00 [queued]>
[2025-06-19T10:46:56.303+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-19T10:46:57.044+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_pbp_from_stg_and_transform> on 2025-06-19 10:46:54.023225+00:00
[2025-06-19T10:46:57.063+0000] {standard_task_runner.py:63} INFO - Started process 1987 to run task
[2025-06-19T10:46:57.073+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_staging_to_transform', 'fetch_pbp_from_stg_and_transform', 'manual__2025-06-19T10:46:54.023225+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp6csshjju']
[2025-06-19T10:46:57.077+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask fetch_pbp_from_stg_and_transform
[2025-06-19T10:46:57.240+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_staging_to_transform.fetch_pbp_from_stg_and_transform manual__2025-06-19T10:46:54.023225+00:00 [running]> on host 11d91b3c2b82
[2025-06-19T10:46:57.522+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_staging_to_transform' AIRFLOW_CTX_TASK_ID='fetch_pbp_from_stg_and_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T10:46:54.023225+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T10:46:54.023225+00:00'
[2025-06-19T10:46:57.525+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-19T10:46:57.604+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/etl_pipeline.py:561 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-19T10:46:57.609+0000] {logging_mixin.py:188} INFO - Failed to fetch play-by-play data from database: Execution failed on sql '
                            SELECT * FROM stgpbp
                            ': relation "stgpbp" does not exist
LINE 2:                             SELECT * FROM stgpbp
                                                  ^
[2025-06-19T10:46:57.610+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-19T10:46:57.612+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2262, in execute
    cur.execute(sql, *args)
psycopg2.errors.UndefinedTable: relation "stgpbp" does not exist
LINE 2:                             SELECT * FROM stgpbp
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 561, in fetch_transform_pbp
    df = pd.read_sql("""
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 654, in read_sql
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2326, in read_query
    cursor = self.execute(sql, params)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2274, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
                            SELECT * FROM stgpbp
                            ': relation "stgpbp" does not exist
LINE 2:                             SELECT * FROM stgpbp
                                                  ^

[2025-06-19T10:46:57.643+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_staging_to_transform, task_id=fetch_pbp_from_stg_and_transform, run_id=manual__2025-06-19T10:46:54.023225+00:00, execution_date=20250619T104654, start_date=20250619T104656, end_date=20250619T104657
[2025-06-19T10:46:57.762+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task fetch_pbp_from_stg_and_transform (Execution failed on sql '
                            SELECT * FROM stgpbp
                            ': relation "stgpbp" does not exist
LINE 2:                             SELECT * FROM stgpbp
                                                  ^
; 1987)
[2025-06-19T10:46:57.813+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-19T10:46:57.849+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T10:46:57.916+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
