[2025-06-15T21:38:45.579+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T21:38:45.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_schedule_and_load_to_postgres manual__2025-06-15T21:38:43.259790+00:00 [queued]>
[2025-06-15T21:38:45.620+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_schedule_and_load_to_postgres manual__2025-06-15T21:38:43.259790+00:00 [queued]>
[2025-06-15T21:38:45.621+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-15T21:38:45.666+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_schedule_and_load_to_postgres> on 2025-06-15 21:38:43.259790+00:00
[2025-06-15T21:38:45.674+0000] {standard_task_runner.py:63} INFO - Started process 564 to run task
[2025-06-15T21:38:45.681+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_postgres', 'fetch_schedule_and_load_to_postgres', 'manual__2025-06-15T21:38:43.259790+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpwh6wswg4']
[2025-06-15T21:38:45.683+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask fetch_schedule_and_load_to_postgres
[2025-06-15T21:38:45.823+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_postgres.fetch_schedule_and_load_to_postgres manual__2025-06-15T21:38:43.259790+00:00 [running]> on host 987366f3af32
[2025-06-15T21:38:46.013+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_schedule_and_load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T21:38:43.259790+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-15T21:38:43.259790+00:00'
[2025-06-15T21:38:46.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T21:38:46.059+0000] {logging_mixin.py:188} INFO - Fetching schedule from NBA API...
[2025-06-15T21:38:47.066+0000] {logging_mixin.py:188} INFO - Successfully fetched and transformed 1321 games.
[2025-06-15T21:38:47.067+0000] {logging_mixin.py:188} INFO - Preparing to load data into staging table: stgschedule
[2025-06-15T21:38:47.071+0000] {logging_mixin.py:188} INFO - Database execution error: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "nbadatabase" does not exist
[2025-06-15T21:38:47.072+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T21:38:47.072+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 120, in fetch_and_load_schedule_to_stage
    load_df_to_postgres(df=df, table_name=table_name, conn_string=conn_string, create_table_query=create_table_query)
  File "/opt/airflow/dags/etl_pipeline.py", line 50, in load_df_to_postgres
    with psycopg2.connect(conn_string) as conn:
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "nbadatabase" does not exist

[2025-06-15T21:38:47.086+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_etl_to_postgres, task_id=fetch_schedule_and_load_to_postgres, run_id=manual__2025-06-15T21:38:43.259790+00:00, execution_date=20250615T213843, start_date=20250615T213845, end_date=20250615T213847
[2025-06-15T21:38:47.147+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task fetch_schedule_and_load_to_postgres (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "nbadatabase" does not exist
; 564)
[2025-06-15T21:38:47.182+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-15T21:38:47.205+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-15T21:38:47.242+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
