[2025-06-20T15:28:21.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-20T15:28:21.213+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_transform_to_dwh.load_fc_shoot manual__2025-06-20T15:26:10.935210+00:00 [queued]>
[2025-06-20T15:28:21.221+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_transform_to_dwh.load_fc_shoot manual__2025-06-20T15:26:10.935210+00:00 [queued]>
[2025-06-20T15:28:21.222+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-20T15:28:21.265+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_fc_shoot> on 2025-06-20 15:26:10.935210+00:00
[2025-06-20T15:28:21.270+0000] {standard_task_runner.py:63} INFO - Started process 2931 to run task
[2025-06-20T15:28:21.275+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_transform_to_dwh', 'load_fc_shoot', 'manual__2025-06-20T15:26:10.935210+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpf1dd2wxp']
[2025-06-20T15:28:21.276+0000] {standard_task_runner.py:91} INFO - Job 261: Subtask load_fc_shoot
[2025-06-20T15:28:21.362+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_transform_to_dwh.load_fc_shoot manual__2025-06-20T15:26:10.935210+00:00 [running]> on host 5ea278fdf3a6
[2025-06-20T15:28:21.505+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_transform_to_dwh' AIRFLOW_CTX_TASK_ID='load_fc_shoot' AIRFLOW_CTX_EXECUTION_DATE='2025-06-20T15:26:10.935210+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-20T15:26:10.935210+00:00'
[2025-06-20T15:28:21.506+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-20T15:28:21.522+0000] {etl_pipeline.py:562} INFO - Ensuring dimension table 'fcshoot' exists...
[2025-06-20T15:28:21.588+0000] {etl_pipeline.py:564} INFO - Loading/updating data into 'fcshoot'...
[2025-06-20T15:28:21.590+0000] {etl_pipeline.py:568} ERROR - Failed to create or load dimension 'fcshoot'. Error: column tsc.hometeam does not exist
LINE 14:                     JOIN dimmatch dm on tsc.hometeam = dm.ho...
                                                 ^
HINT:  Perhaps you meant to reference the column "dm.hometeam".

[2025-06-20T15:28:21.591+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-20T15:28:21.591+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 565, in create_fc_shoot
    cursor.execute(insert_query)
psycopg2.errors.UndefinedColumn: column tsc.hometeam does not exist
LINE 14:                     JOIN dimmatch dm on tsc.hometeam = dm.ho...
                                                 ^
HINT:  Perhaps you meant to reference the column "dm.hometeam".

[2025-06-20T15:28:21.606+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_transform_to_dwh, task_id=load_fc_shoot, run_id=manual__2025-06-20T15:26:10.935210+00:00, execution_date=20250620T152610, start_date=20250620T152821, end_date=20250620T152821
[2025-06-20T15:28:21.647+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 261 for task load_fc_shoot (column tsc.hometeam does not exist
LINE 14:                     JOIN dimmatch dm on tsc.hometeam = dm.ho...
                                                 ^
HINT:  Perhaps you meant to reference the column "dm.hometeam".
; 2931)
[2025-06-20T15:28:21.689+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-20T15:28:21.710+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-20T15:28:21.738+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
