[2025-06-20T18:49:40.372+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-20T18:49:40.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_transform_to_dwh.load_fc_shoot manual__2025-06-20T18:47:28.416575+00:00 [queued]>
[2025-06-20T18:49:40.410+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_transform_to_dwh.load_fc_shoot manual__2025-06-20T18:47:28.416575+00:00 [queued]>
[2025-06-20T18:49:40.411+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-20T18:49:40.451+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_fc_shoot> on 2025-06-20 18:47:28.416575+00:00
[2025-06-20T18:49:40.458+0000] {standard_task_runner.py:63} INFO - Started process 4478 to run task
[2025-06-20T18:49:40.463+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_transform_to_dwh', 'load_fc_shoot', 'manual__2025-06-20T18:47:28.416575+00:00', '--job-id', '315', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpjyn4sb27']
[2025-06-20T18:49:40.464+0000] {standard_task_runner.py:91} INFO - Job 315: Subtask load_fc_shoot
[2025-06-20T18:49:40.559+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_transform_to_dwh.load_fc_shoot manual__2025-06-20T18:47:28.416575+00:00 [running]> on host 5ea278fdf3a6
[2025-06-20T18:49:40.700+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_transform_to_dwh' AIRFLOW_CTX_TASK_ID='load_fc_shoot' AIRFLOW_CTX_EXECUTION_DATE='2025-06-20T18:47:28.416575+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-20T18:47:28.416575+00:00'
[2025-06-20T18:49:40.703+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-20T18:49:40.721+0000] {etl_pipeline.py:564} INFO - Ensuring dimension table 'fcshoot' exists...
[2025-06-20T18:49:40.802+0000] {etl_pipeline.py:566} INFO - Loading/updating data into 'fcshoot'...
[2025-06-20T18:49:40.809+0000] {etl_pipeline.py:570} ERROR - Failed to create or load dimension 'fcshoot'. Error: column tsc.makemiss does not exist
LINE 6:                         tsc.makemiss, 
                                ^
HINT:  Perhaps you meant to reference the column "tsc.make_miss".

[2025-06-20T18:49:40.810+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-20T18:49:40.812+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 567, in create_fc_shoot
    cursor.execute(insert_query)
psycopg2.errors.UndefinedColumn: column tsc.makemiss does not exist
LINE 6:                         tsc.makemiss, 
                                ^
HINT:  Perhaps you meant to reference the column "tsc.make_miss".

[2025-06-20T18:49:40.857+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_transform_to_dwh, task_id=load_fc_shoot, run_id=manual__2025-06-20T18:47:28.416575+00:00, execution_date=20250620T184728, start_date=20250620T184940, end_date=20250620T184940
[2025-06-20T18:49:40.909+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 315 for task load_fc_shoot (column tsc.makemiss does not exist
LINE 6:                         tsc.makemiss, 
                                ^
HINT:  Perhaps you meant to reference the column "tsc.make_miss".
; 4478)
[2025-06-20T18:49:40.957+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-20T18:49:40.975+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-20T18:49:41.000+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
