[2025-06-15T20:38:11.141+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T20:38:11.174+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage manual__2025-06-15T20:37:56.510794+00:00 [queued]>
[2025-06-15T20:38:11.184+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage manual__2025-06-15T20:37:56.510794+00:00 [queued]>
[2025-06-15T20:38:11.184+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-15T20:38:11.253+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_load_teams_to_stage> on 2025-06-15 20:37:56.510794+00:00
[2025-06-15T20:38:11.287+0000] {standard_task_runner.py:63} INFO - Started process 863 to run task
[2025-06-15T20:38:11.291+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_postgres', 'fetch_and_load_teams_to_stage', 'manual__2025-06-15T20:37:56.510794+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp4zhyf2p9']
[2025-06-15T20:38:11.292+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask fetch_and_load_teams_to_stage
[2025-06-15T20:38:11.411+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage manual__2025-06-15T20:37:56.510794+00:00 [running]> on host 1c61638087f1
[2025-06-15T20:38:11.924+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_and_load_teams_to_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T20:37:56.510794+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-15T20:37:56.510794+00:00'
[2025-06-15T20:38:11.926+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T20:38:14.168+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T20:38:14.169+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 283, in fetch_and_load_teams_to_stage
    cur.copy_expert(sql_copy_command, f)
psycopg2.errors.UndefinedTable: relation "stgteam" does not exist

[2025-06-15T20:38:14.215+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_etl_to_postgres, task_id=fetch_and_load_teams_to_stage, run_id=manual__2025-06-15T20:37:56.510794+00:00, execution_date=20250615T203756, start_date=20250615T203811, end_date=20250615T203814
[2025-06-15T20:38:14.297+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task fetch_and_load_teams_to_stage (relation "stgteam" does not exist
; 863)
[2025-06-15T20:38:14.345+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-15T20:38:14.356+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
